version: "3.7"

services:
  dp:
    image: sajadsadra/dnsify_proxy:latest
    environment:
      - DP_PASSWORD=yourpass
      - DP_EMAIL=user@example.ex
      - DP_NS=example.ex
    ports:
      - "443:443/tcp"
      - "53:53/udp"
      - "53:53/tcp"
      - "23:8585"
    volumes:
      - dnsdir:/etc/bind
      - proxydir:/etc/haproxy

volumes:
  dnsdir:
  proxydir:
