version: "3.7"

services: 

  dns-proxy:
    image: defreitas/dns-proxy-server:2.19.0
    restart: always
    ports: 
      - "53:53/udp"
      - "8080:5380" 
    volumes: 
      - ./conf/:/app/conf/
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/resolv.conf:/etc/resolv.conf
      
  nginx:
    image: sajadsadra/proxy-pass:latest
    restart: always
    ports: 
      - 80:80
      - 443:443

