version: "3.7"

services:
  dp:
    image: sajadsadra/dnsify_proxy:latest
    environment:
      - DP_PASSWORD=yourpass
      - DP_EMAIL=user@example.ex
      - DP_NS=example.ex
    ports:
      - "53:53/udp"
      - "53:53/tcp"
      - "23:8585"
    volumes:
      - ./dockerImage/panel_API/bind:/etc/bind
      - ./dockerImage/panel_API/haproxy:/etc/haproxy
